ui <- shiny::fluidPage(
  shiny::tags$head(
    shiny::includeCSS("www/style.css")
  ),
  shinyjs::useShinyjs(),
  shiny::titlePanel("SUD_MSNA_HH_survey shiny App"),
  shiny::sidebarLayout(
    shiny::sidebarPanel(
      shiny::selectizeInput(
        'action', "What type of actions you want to perform:", choices = setNames(c("clog","clean","xml_tolabel"),c("Produce a cleaning LOG","Clean DATA","Convert to labeled DATA")),
        options = list(
          placeholder = 'Please choose one of the following actions',
          onInitialize = I('function() { this.setValue(""); }')
        )
      ),
      shiny::uiOutput("ui.f2f_phone"),
      shiny::tags$hr(),
      shiny::uiOutput("ui.cloglabel"),
      shiny::tags$hr(),
      shiny::uiOutput("ui.db"),
      shiny::uiOutput("ui.questionnaire"),
      shiny::uiOutput("ui.choiceslabel"),
      shiny::uiOutput("ui.surveylabel"),
      shiny::uiOutput("ui.clog"),
      shiny::tags$hr(),
      shiny::actionButton("runchecks","RUN checks"),
      shiny::actionButton("runclean","CLEAN data"),
      shiny::actionButton("runconv","CONVERTIR"),
      shiny::tags$hr(),
      shiny::downloadButton("dwclog"),
      shiny::downloadButton("dwclean"),
      shiny::downloadButton("dwconv"),
      shiny::helpText("Download will be available once the processing is completed.")
    )
    ,
    shiny::mainPanel(
      shiny::conditionalPanel(condition="$('html').hasClass('shiny-busy')",
                              shiny::tags$div("Loading...",id="loadmessage")),
      p("Welcome to Sudan MSNA shiny app. This tool was developed to make the typical workflow of AO's, IM Officers smoother and less complicated. The app will help users run their data checks and clean the data in a more efficient and automated way. No need for strong R background and technical capacities."),
      p("What this app will do for you."),
      p("1/ Produce a Cleaning LOG"),
      p("2/ Clean DATA"),
      p("3/ Label the XML headers and values"),
      h3(strong("Produce a Cleaning LOG"),style ="color:#EE5859"),
      p("When the user pick this option in the drop-down list", strong("What type of actions you want to perform"), "several fied inputs will pop-up."),
      p(strong("Data Collection Method")," : Face to face or Telephone"),
      p("Since the checks may differ between the different types of the DC, the user should carefully choose the right option."),
      p("The app allow the user to label the questions and the answers by clicking",strong("Yes"), "to", strong("Do you want to label questions/choices in the Cleaning LOG?")),
      p(strong("DATASET (.csv or .xlsx) :")),
      p("The user can upload the file either in a .csv format or .xlsx/xls.",code("Data format is really IMPORTANT to be able to use this app without facing any issues.")),
      p(strong("Value and header format should be in XML")),
      p(strong("Do not include groups in headers")),
      p(strong("Group separator should be a point (.)")),
      p("To have such format, when downloading DATA from KOBO the user should:"),
      p(strong("Select the option XML values and headers in the field value and header format")),
      p(strong("Untick Include groups in headers")),
      p(strong("Put a dot (.) in group seperator field")),
      p("A tidy dataset should have a unique identifier 'uuid' and not have duplicated variables. Make sure the imported data follow those rules. Your dataset should be aligned with the data collection tool!"),
      p(strong("EXCEL workbook Questionnaire:")),
      p("Upload your XLSform (data collection tool) with the", strong("survey")," and", strong("choices"), "tabs. Place your questions of type text for", strong("other"), "immediately after their parent questions (select_one/select_multiple). To detect all 'other' columns, headers should end with other"),
      p("Select your choices/survey label columns."),
      p("You can label your cleaning LOG by selecting yes in ",strong("Do you want to label question/choices in the cleaning LOG"), "field."),
      p("Once users have uploaded the required inputs, the button", strong("RUN checks"), "will be enabled and they can start the checking. Once computations are done, the button", strong("Download Cleaning LOG"), "will be also enabled to download the cleaning LOG"),
      h3(strong("Clean DATA"),style ="color:#EE5859"),
      p(strong("dataset (.csv or .xlsx) :")),
      p("Please see section above"),
      p(strong("EXCEL workbook Questionnaire :")),
      p("Please see section above"),
      p(strong("Cleaning LOG (.csv or .xlsx)")),
      p("The cleaning LOG that you will produce in the previous section contains:"),
      p(span("uuid",style ="color:#EE5859")," :Unique identifier"),
      p(span("question.name",style ="color:#EE5859")," :XML question name"),
      p(span("old.value",style ="color:#EE5859")),
      p(span("new.value",style ="color:#EE5859")," :If applicable"),
      p(span("parent.other.question",style ="color:#EE5859"), ": The cleaning log will list all 'other' questions, this column will have the parent xml question."),
      p("Example:"),
      p("question.name: food_source_other"),
      p("parent.other.question: food_source"),
      p(span("parent.other.answer",style ="color:#EE5859")," :The cleaning log will list all 'other/autre' answers, this column will have the answers of the parent.other.question. This is helpful to decide if we should keep other as an option, or if a similar option was already selected or if we have a similar option in the list of choices and other should be replaced."),
      p("Example:"),
      p("question.name: food_source_other"),
      p("parent.other.question: food_source"),
      p("parent.other.answer: own_production food_aid other"),
      p(span("action",style ="color:#EE5859"), " :we specify how to treat each row of the cleaning log. Below the different possible actions (inspired from Olivier Cecchi scripts)"),
      p(span("check",style ="color:#58585A"), " :No action will be performed"),
      p(span("remove",style ="color:#58585A"), " :Survey will be removed"),
      p(span("change",style ="color:#58585A"), " :old.value will be replaced by new.value for question.name"),
      p(span("recode",style ="color:#58585A"), " :parent.other.answer will be replaced by new.value for parent.other.question"),
      p(span("recode_all",style ="color:#58585A"), " :all answers of question.name that matches old.value will be replaced by new.value"),
      p(strong("NB: For select_multiple questions cleaning, we focus on the non-binary columns, the app will automatically update all the binary columns"),
      p("Once users uploaded the required inputs, the button", strong("CLEAN data"), "will be enabled and they can start the cleaning. Once computations are done, the button", strong("Download clean data"), "will be also enabled to download the Output.")),
      h3(strong("Convert XML to LABEL"),style ="color:#EE5859"),
      p(strong("dataset/ donnees (.csv or .xlsx):")),
      p("Please see section above"),
      p(strong("EXCEL Questionnaire workbook :")),
      p("Please see section above"),
      p("As you might have guessed, this action will label your XML formatted data."),
      p(strong("REMINDER: Value and header format should be in XML, do not include groups in headers, group separator should be a point (.), dp not have duplicated columns. If questions/options were added, update your XLSform tool.")),
      p("Once users uploaded the required inputs, the button", strong("CONVERT data"), "will be enabled. Once computations are done, the button", strong("Download Converted DATA"), "will be also enabled to download the Output."),
      shiny::br()
    )
  )
)
